# Generated by Django 2.0.2 on 2018-02-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demarcation_code', models.CharField(max_length=255)),
                ('demarcation_label', models.CharField(max_length=255)),
                ('financial_year_end', models.CharField(max_length=255)),
                ('opinion', models.CharField(max_length=255)),
                ('opinion_report_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=255)),
                ('demarcation_code', models.CharField(max_length=255)),
                ('demarcation_label', models.CharField(max_length=255)),
                ('financial_year_end', models.CharField(max_length=255)),
                ('item_label', models.CharField(max_length=255)),
                ('amount_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=255)),
                ('amount_type', models.CharField(max_length=255)),
                ('financial_year_end', models.CharField(max_length=255)),
                ('item_label', models.CharField(max_length=255)),
                ('demarcation_code', models.CharField(max_length=255)),
                ('demarcation_label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demarcation_code', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('amount_type', models.CharField(max_length=255)),
                ('financial_year_end', models.CharField(max_length=255)),
                ('item_label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demarcation_code', models.CharField(max_length=255)),
                ('kpi', models.CharField(max_length=255)),
                ('forecast_period', models.CharField(max_length=255)),
                ('forecast_value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=255)),
                ('amount_type', models.CharField(max_length=255)),
                ('financial_year_end', models.CharField(max_length=255)),
                ('item_label', models.CharField(max_length=255)),
                ('demarcation_code', models.CharField(max_length=255)),
                ('demarcation_label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demarcation_code', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('amount_type', models.CharField(max_length=255)),
                ('financial_year_end', models.CharField(max_length=255)),
                ('item_label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Municipalities',
            fields=[
                ('area', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('demarcation_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fax_number', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('postal_address_1', models.CharField(max_length=255)),
                ('postal_address_2', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('province_name', models.CharField(max_length=255)),
                ('street_address_1', models.CharField(max_length=255)),
                ('street_address_2', models.CharField(max_length=255)),
                ('street_address_3', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('audits', models.ManyToManyField(to='app.Audits')),
                ('balance_sheets', models.ManyToManyField(to='app.BalanceSheet')),
                ('capital', models.ManyToManyField(to='app.Capital')),
                ('cash_flows', models.ManyToManyField(to='app.CashFlow')),
                ('forecasts', models.ManyToManyField(to='app.Forecast')),
                ('income_expense', models.ManyToManyField(to='app.IncomeExpense')),
                ('maintenance', models.ManyToManyField(to='app.Maintenance')),
            ],
        ),
        migrations.CreateModel(
            name='Officials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('fax_number', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('demarcation_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WastefulExpenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=255)),
                ('demarcation_code', models.CharField(max_length=255)),
                ('demarcation_label', models.CharField(max_length=255)),
                ('financial_year_end', models.CharField(max_length=255)),
                ('item_label', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='wastefulexpenditure',
            unique_together={('demarcation_code', 'item_label', 'financial_year_end')},
        ),
        migrations.AlterUniqueTogether(
            name='officials',
            unique_together={('demarcation_code', 'role')},
        ),
        migrations.AddField(
            model_name='municipalities',
            name='officials',
            field=models.ManyToManyField(to='app.Officials'),
        ),
        migrations.AddField(
            model_name='municipalities',
            name='wasteful',
            field=models.ManyToManyField(to='app.WastefulExpenditure'),
        ),
        migrations.AlterUniqueTogether(
            name='maintenance',
            unique_together={('demarcation_code', 'item_label', 'amount_type', 'financial_year_end')},
        ),
        migrations.AlterUniqueTogether(
            name='incomeexpense',
            unique_together={('demarcation_code', 'amount_type', 'financial_year_end', 'item_label')},
        ),
        migrations.AlterUniqueTogether(
            name='forecast',
            unique_together={('demarcation_code', 'kpi', 'forecast_period')},
        ),
        migrations.AlterUniqueTogether(
            name='cashflow',
            unique_together={('demarcation_code', 'item_label', 'financial_year_end', 'amount_type')},
        ),
        migrations.AlterUniqueTogether(
            name='capital',
            unique_together={('demarcation_code', 'amount_type', 'financial_year_end', 'item_label')},
        ),
        migrations.AlterUniqueTogether(
            name='balancesheet',
            unique_together={('demarcation_code', 'item_label', 'financial_year_end', 'amount_type')},
        ),
        migrations.AlterUniqueTogether(
            name='audits',
            unique_together={('demarcation_code', 'financial_year_end', 'opinion')},
        ),
    ]
